// ── Form Design Presets ──────────────────────────────────────────────────────
// layout: "fullscreen" → covers whole screen (classic)
// layout: "floating"   → centered card/modal over blurred overlay
//
// Floating-only props:
//   overlayBg   → backdrop style
//   cardBg      → inner card background
//   cardMaxWidth→ tailwind max-w class for the card
//   accentBar   → colored strip shown at top of card (optional)
//   submitClass → override primary button class

export const FORM_DESIGN_CONFIGS = {
  // ── 1. Aurora — Fullscreen vidrio ──────────────────────────────────────────
  aurora: {
    name: "Aurora",
    hint: "Pantalla completa",
    layout: "fullscreen",
    containerBg: "linear-gradient(135deg,rgba(238,242,255,0.98),rgba(248,250,255,0.98),rgba(240,248,255,0.98))",
    barClass: "border-slate-200/60 bg-white/40",
    inp: "w-full text-base px-5 py-4 rounded-2xl bg-white/70 border-2 border-white/80 focus:outline-none focus:border-[var(--t-from)] focus:bg-white text-slate-800 placeholder-slate-400 font-medium transition-all duration-200",
    labelClass: "block text-xs font-black text-slate-500 uppercase tracking-widest mb-2",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-slate-900",
    cancelClass: "glass border-slate-200/60 text-slate-600 hover:bg-white/80",
    isDark: false,
    previewLayout: "fullscreen",
    previewBg: "linear-gradient(135deg,rgba(200,210,255,0.35),rgba(220,235,255,0.35))",
    previewBar: "rgba(255,255,255,0.5)", previewInp: "rgba(255,255,255,0.68)",
    previewBorder: "rgba(255,255,255,0.88)", previewUnderlineOnly: false,
  },

  // ── 2. Flotante — Tarjeta blanca centrada ─────────────────────────────────
  flotante: {
    name: "Flotante",
    hint: "Tarjeta centrada",
    layout: "floating",
    overlayBg: "rgba(15,23,42,0.55)",
    overlayBlur: "blur(14px)",
    cardBg: "#ffffff",
    cardMaxWidth: "max-w-3xl",
    cardRadius: "rounded-3xl",
    cardShadow: "shadow-[0_32px_80px_-12px_rgba(0,0,0,0.35)]",
    barClass: "border-slate-100 bg-slate-50/80",
    inp: "w-full text-sm px-4 py-3 rounded-xl bg-white border border-slate-200 focus:outline-none focus:border-[var(--t-from)] focus:ring-2 focus:ring-[var(--t-from)]/20 text-slate-800 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-slate-900",
    cancelClass: "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50",
    isDark: false,
    previewLayout: "floating",
    previewOverlay: "rgba(15,23,42,0.55)",
    previewBg: "#ffffff",
    previewBar: "#f8fafc", previewInp: "#f1f5f9",
    previewBorder: "#e2e8f0", previewUnderlineOnly: false,
  },

  // ── 3. Tarjeta — Card con barra de acento superior ────────────────────────
  tarjeta: {
    name: "Tarjeta",
    hint: "Card con acento",
    layout: "floating",
    overlayBg: "rgba(15,23,42,0.6)",
    overlayBlur: "blur(16px)",
    cardBg: "#ffffff",
    cardMaxWidth: "max-w-3xl",
    cardRadius: "rounded-2xl",
    cardShadow: "shadow-[0_24px_60px_-8px_rgba(0,0,0,0.3)]",
    accentBar: "linear-gradient(90deg,var(--t-from),var(--t-to))",
    barClass: "border-white/0 bg-transparent",
    inp: "w-full text-sm px-4 py-3 rounded-xl bg-slate-50 border-2 border-slate-100 focus:outline-none focus:border-[var(--t-from)] text-slate-800 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-white",
    cancelClass: "bg-white/20 border border-white/40 text-white hover:bg-white/30",
    isDark: false,
    previewLayout: "floating",
    previewOverlay: "rgba(15,23,42,0.6)",
    previewBg: "#ffffff",
    previewAccent: "var(--t-from)",
    previewBar: "linear-gradient(90deg,var(--t-from),var(--t-to))", previewInp: "#f1f5f9",
    previewBorder: "#e2e8f0", previewUnderlineOnly: false,
  },

  // ── 4. Popup Oscuro — Modal dark compacto ────────────────────────────────
  popup: {
    name: "Popup",
    hint: "Modal oscuro",
    layout: "floating",
    overlayBg: "rgba(0,0,0,0.78)",
    overlayBlur: "blur(20px)",
    cardBg: "#1e293b",
    cardMaxWidth: "max-w-2xl",
    cardRadius: "rounded-3xl",
    cardShadow: "shadow-[0_40px_100px_-10px_rgba(0,0,0,0.7)]",
    barClass: "border-white/10 bg-white/5",
    inp: "w-full text-sm px-4 py-3 rounded-xl bg-white/8 border border-white/15 focus:outline-none focus:border-[var(--t-from)] focus:bg-white/12 text-white placeholder-white/30 font-medium transition-all",
    labelClass: "block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-white",
    cancelClass: "bg-white/10 border border-white/20 text-white/70 hover:bg-white/15",
    isDark: true,
    previewLayout: "floating",
    previewOverlay: "rgba(0,0,0,0.78)",
    previewBg: "#1e293b",
    previewBar: "rgba(255,255,255,0.06)", previewInp: "rgba(255,255,255,0.08)",
    previewBorder: "rgba(255,255,255,0.15)", previewUnderlineOnly: false,
  },

  // ── 5. App — Dark con gradiente verde (inspiración mobile) ───────────────
  app: {
    name: "App",
    hint: "Estilo app oscuro",
    layout: "floating",
    overlayBg: "rgba(0,0,0,0.88)",
    overlayBlur: "blur(24px)",
    cardBg: "#0d1117",
    cardMaxWidth: "max-w-2xl",
    cardRadius: "rounded-3xl",
    cardShadow: "shadow-[0_40px_100px_-8px_rgba(0,0,0,0.8)]",
    accentBar: "linear-gradient(90deg,#16a34a,#22c55e,#4ade80)",
    barClass: "border-white/5 bg-black/40",
    inp: "w-full text-sm px-4 py-3 rounded-xl bg-white/6 border border-[var(--t-from)]/30 focus:outline-none focus:border-[var(--t-from)] text-white placeholder-white/25 font-medium transition-all",
    labelClass: "block text-[10px] font-black uppercase tracking-widest mb-1.5",
    labelStyle: { color: "#4ade80" },
    inpStyle: undefined,
    titleClass: "text-white",
    cancelClass: "bg-white/5 border border-white/10 text-white/60 hover:bg-white/10",
    isDark: true,
    previewLayout: "floating",
    previewOverlay: "rgba(0,0,0,0.88)",
    previewBg: "#0d1117",
    previewBar: "linear-gradient(90deg,#16a34a,#22c55e)", previewInp: "rgba(255,255,255,0.06)",
    previewBorder: "rgba(74,222,128,0.35)", previewUnderlineOnly: false, previewIsGreen: true,
  },

  // ── 6. Minimalista — Limpio puro ─────────────────────────────────────────
  minimal: {
    name: "Minimal",
    hint: "Líneas limpias",
    layout: "floating",
    overlayBg: "rgba(248,250,252,0.85)",
    overlayBlur: "blur(8px)",
    cardBg: "#ffffff",
    cardMaxWidth: "max-w-2xl",
    cardRadius: "rounded-2xl",
    cardShadow: "shadow-[0_8px_40px_-4px_rgba(0,0,0,0.12)]",
    barClass: "border-slate-100 bg-white",
    inp: "w-full text-sm px-1 py-3 bg-transparent border-0 border-b border-slate-200 focus:outline-none focus:border-[var(--t-from)] text-slate-800 placeholder-slate-300 font-medium transition-all rounded-none",
    labelClass: "block text-[9px] font-black text-slate-400 uppercase tracking-[0.15em] mb-1",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-slate-900",
    cancelClass: "text-slate-400 hover:text-slate-700 transition-colors",
    isDark: false,
    previewLayout: "floating",
    previewOverlay: "rgba(248,250,252,0.85)",
    previewBg: "#ffffff",
    previewBar: "#ffffff", previewInp: "transparent",
    previewBorder: "#e2e8f0", previewUnderlineOnly: true,
  },

  // ── 7. Cristal — Glass blur effect ───────────────────────────────────────
  cristal: {
    name: "Cristal",
    hint: "Vidrio flotante",
    layout: "floating",
    overlayBg: "linear-gradient(135deg,rgba(56,189,248,0.18),rgba(99,102,241,0.14))",
    overlayBlur: "blur(20px)",
    cardBg: "rgba(255,255,255,0.75)",
    cardBackdrop: "blur(24px) saturate(180%)",
    cardMaxWidth: "max-w-3xl",
    cardRadius: "rounded-3xl",
    cardShadow: "shadow-[0_24px_60px_-8px_rgba(99,102,241,0.25)]",
    barClass: "border-white/50 bg-white/30",
    inp: "w-full text-sm px-4 py-3 rounded-xl bg-white/60 border border-sky-200/70 focus:outline-none focus:border-[var(--t-from)] focus:bg-white text-slate-800 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-[10px] font-black text-sky-700/80 uppercase tracking-widest mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-slate-800",
    cancelClass: "bg-white/50 border border-white/60 text-slate-600 hover:bg-white/80",
    isDark: false,
    previewLayout: "floating",
    previewOverlay: "linear-gradient(135deg,rgba(56,189,248,0.18),rgba(99,102,241,0.14))",
    previewBg: "rgba(255,255,255,0.75)",
    previewBar: "rgba(255,255,255,0.35)", previewInp: "rgba(255,255,255,0.6)",
    previewBorder: "#bae6fd", previewUnderlineOnly: false,
  },
};

export const FORM_DESIGN_ORDER = ["aurora", "flotante", "tarjeta", "popup", "app", "minimal", "cristal"];
