// ── Form Design Presets ──────────────────────────────────────────────────────
// Shared config used by AppearancePage (previews) and form components (styling)

export const FORM_DESIGN_CONFIGS = {
  aurora: {
    name: "Aurora",
    hint: "Vidrio gradiente",
    containerBg: "linear-gradient(135deg, rgba(238,242,255,0.98) 0%, rgba(248,250,255,0.98) 50%, rgba(240,248,255,0.98) 100%)",
    barClass: "border-slate-200/60 bg-white/40",
    inp: "w-full text-base px-5 py-4 rounded-2xl bg-white/70 border-2 border-white/80 focus:outline-none focus:border-[var(--t-from)] focus:bg-white text-slate-800 placeholder-slate-400 font-medium transition-all duration-200",
    labelClass: "block text-xs font-black text-slate-500 uppercase tracking-widest mb-2",
    labelStyle: undefined,
    inpStyle: undefined,
    titleClass: "text-slate-900",
    cancelClass: "glass border-slate-200/60 text-slate-600 hover:bg-white/80",
    isDark: false,
    // Preview data
    previewBg: "linear-gradient(135deg,rgba(200,210,255,0.35),rgba(220,235,255,0.35))",
    previewBar: "rgba(255,255,255,0.5)",
    previewInp: "rgba(255,255,255,0.68)",
    previewBorder: "rgba(255,255,255,0.88)",
    previewUnderlineOnly: false,
  },
  limpio: {
    name: "Limpio",
    hint: "Blanco plano",
    containerBg: "#ffffff",
    barClass: "border-slate-200 bg-slate-50",
    inp: "w-full text-base px-5 py-4 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:border-[var(--t-from)] focus:bg-white text-slate-800 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-xs font-semibold text-slate-500 mb-2",
    labelStyle: undefined,
    inpStyle: undefined,
    titleClass: "text-slate-900",
    cancelClass: "bg-white border border-slate-200 text-slate-600 hover:bg-slate-100",
    isDark: false,
    previewBg: "#ffffff",
    previewBar: "#f8fafc",
    previewInp: "#f1f5f9",
    previewBorder: "#e2e8f0",
    previewUnderlineOnly: false,
  },
  compacto: {
    name: "Compacto",
    hint: "Denso y claro",
    containerBg: "linear-gradient(160deg, #f8fafc 0%, #f1f5f9 100%)",
    barClass: "border-slate-200 bg-slate-100",
    inp: "w-full text-sm px-4 py-2.5 rounded-xl bg-white border border-slate-200 focus:outline-none focus:border-[var(--t-from)] text-slate-700 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5",
    labelStyle: undefined,
    inpStyle: undefined,
    titleClass: "text-slate-800",
    cancelClass: "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50",
    isDark: false,
    previewBg: "linear-gradient(160deg,#f8fafc,#f1f5f9)",
    previewBar: "#e2e8f0",
    previewInp: "#ffffff",
    previewBorder: "#e2e8f0",
    previewUnderlineOnly: false,
  },
  oscuro: {
    name: "Oscuro",
    hint: "Elegante oscuro",
    containerBg: "linear-gradient(135deg, #0f172a 0%, #1e293b 60%, #0f172a 100%)",
    barClass: "border-white/10 bg-slate-900/70",
    inp: "w-full text-base px-5 py-4 rounded-2xl bg-white/10 border border-white/15 focus:outline-none focus:border-[var(--t-from)] text-white placeholder-white/30 font-medium transition-all",
    labelClass: "block text-xs font-black text-slate-400 uppercase tracking-widest mb-2",
    labelStyle: undefined,
    inpStyle: undefined,
    titleClass: "text-white",
    cancelClass: "bg-white/10 border border-white/20 text-white/80 hover:bg-white/20",
    isDark: true,
    previewBg: "linear-gradient(135deg,#0f172a,#1e293b)",
    previewBar: "rgba(0,0,0,0.45)",
    previewInp: "rgba(255,255,255,0.09)",
    previewBorder: "rgba(255,255,255,0.14)",
    previewUnderlineOnly: false,
  },
  neon: {
    name: "Neón",
    hint: "Brillo oscuro",
    containerBg: "linear-gradient(135deg, #020617 0%, #0a0f1e 100%)",
    barClass: "border-white/5 bg-black/55",
    inp: "w-full text-base px-5 py-4 rounded-2xl bg-transparent border border-[var(--t-from)] focus:outline-none text-white placeholder-white/20 font-medium transition-all",
    labelClass: "block text-xs font-black uppercase tracking-widest mb-2",
    labelStyle: { color: "var(--t-from)" },
    inpStyle: { boxShadow: "0 0 14px -3px var(--t-from)55, inset 0 0 0 1px var(--t-from)22" },
    titleClass: "text-white",
    cancelClass: "bg-white/5 border border-[var(--t-from)]/30 text-white/70 hover:bg-white/10",
    isDark: true,
    previewBg: "linear-gradient(135deg,#020617,#0a0f1e)",
    previewBar: "rgba(0,0,0,0.6)",
    previewInp: "transparent",
    previewBorder: "var(--t-from)",
    previewGlow: true,
    previewUnderlineOnly: false,
  },
  editorial: {
    name: "Editorial",
    hint: "Cálido editorial",
    containerBg: "linear-gradient(160deg, #fefce8 0%, #fff7ed 100%)",
    barClass: "border-amber-200/50 bg-amber-50/70",
    inp: "w-full text-base px-2 py-3 bg-transparent border-0 border-b-2 border-amber-200 focus:outline-none focus:border-[var(--t-from)] text-stone-800 placeholder-stone-400 font-medium transition-all",
    labelClass: "block text-xs font-bold text-amber-700/70 uppercase tracking-widest mb-1",
    labelStyle: undefined,
    inpStyle: undefined,
    titleClass: "text-stone-900",
    cancelClass: "bg-amber-50 border border-amber-200 text-stone-600 hover:bg-amber-100",
    isDark: false,
    previewBg: "linear-gradient(160deg,#fefce8,#fff7ed)",
    previewBar: "rgba(254,252,232,0.85)",
    previewInp: "transparent",
    previewBorder: "#fcd34d",
    previewUnderlineOnly: true,
  },
  cristal: {
    name: "Cristal",
    hint: "Azul cristalino",
    containerBg: "linear-gradient(135deg, rgba(186,230,253,0.25) 0%, rgba(240,249,255,0.45) 50%, rgba(224,242,254,0.35) 100%)",
    barClass: "border-sky-200/50 bg-white/60",
    inp: "w-full text-base px-5 py-4 rounded-2xl bg-sky-50/70 border border-sky-200 focus:outline-none focus:border-[var(--t-from)] focus:bg-white text-slate-800 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-xs font-black text-sky-700/70 uppercase tracking-widest mb-2",
    labelStyle: undefined,
    inpStyle: undefined,
    titleClass: "text-slate-800",
    cancelClass: "bg-sky-50 border border-sky-200 text-sky-700/80 hover:bg-sky-100",
    isDark: false,
    previewBg: "linear-gradient(135deg,rgba(186,230,253,0.3),rgba(224,242,254,0.35))",
    previewBar: "rgba(255,255,255,0.62)",
    previewInp: "rgba(240,249,255,0.75)",
    previewBorder: "#bae6fd",
    previewUnderlineOnly: false,
  },
};

export const FORM_DESIGN_ORDER = ["aurora", "limpio", "compacto", "oscuro", "neon", "editorial", "cristal"];
