// ── Form Design Presets ──────────────────────────────────────────────────────
// layout: "fullscreen" → cubre toda la pantalla (clásico)
// layout: "floating"   → tarjeta centrada sobre overlay borroso
//
// Props de floating:
//   overlayBg     → estilo del backdrop
//   overlayBlur   → backdrop-filter
//   cardBg        → fondo de la card
//   cardMaxWidth  → clase tailwind max-w-*
//   accentBar     → barra de color en la parte superior (opcional)

export const FORM_DESIGN_CONFIGS = {

  // ── 1. Aurora — Pantalla completa élite ───────────────────────────────────
  aurora: {
    name: "Aurora",
    hint: "Pantalla completa",
    layout: "fullscreen",
    containerBg: "linear-gradient(160deg,#eef2ff 0%,#f8faff 45%,#f3f0ff 100%)",
    barClass: "border-slate-200/50 bg-white/50",
    inp: "w-full text-sm px-4 py-3.5 rounded-2xl bg-white/80 border border-white/90 focus:outline-none focus:border-[var(--t-from)] focus:ring-2 focus:ring-[var(--t-from)]/15 focus:bg-white text-slate-800 placeholder-slate-400 font-medium transition-all shadow-sm",
    labelClass: "block text-[10px] font-black text-indigo-400/90 uppercase tracking-[0.12em] mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-slate-900",
    cancelClass: "bg-white/80 border border-slate-200/70 text-slate-600 hover:bg-white",
    isDark: false,
    previewLayout: "fullscreen",
    previewBg: "linear-gradient(160deg,#eef2ff,#f3f0ff)",
    previewBar: "rgba(255,255,255,0.5)", previewInp: "rgba(255,255,255,0.85)",
    previewBorder: "rgba(255,255,255,0.95)", previewUnderlineOnly: false,
  },

  // ── 2. Flotante — Tarjeta blanca premium (Stripe / Linear style) ──────────
  flotante: {
    name: "Flotante",
    hint: "Card blanca premium",
    layout: "floating",
    overlayBg: "rgba(30,30,60,0.42)",
    overlayBlur: "blur(18px)",
    cardBg: "#ffffff",
    cardMaxWidth: "max-w-3xl",
    cardRadius: "rounded-3xl",
    cardShadow: "shadow-[0_40px_100px_-15px_rgba(0,0,0,0.4),0_8px_30px_-8px_rgba(0,0,0,0.2)]",
    barClass: "border-slate-100 bg-white",
    inp: "w-full text-sm px-4 py-3.5 rounded-2xl bg-slate-50/80 border border-slate-200 focus:outline-none focus:border-[var(--t-from)] focus:ring-2 focus:ring-[var(--t-from)]/15 focus:bg-white text-slate-800 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-[9px] font-black text-slate-400 uppercase tracking-[0.14em] mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-slate-900",
    cancelClass: "bg-slate-100 text-slate-500 hover:bg-slate-200",
    isDark: false,
    previewLayout: "floating",
    previewOverlay: "rgba(30,30,60,0.42)",
    previewBg: "#ffffff",
    previewBar: "#ffffff", previewInp: "#f8fafc",
    previewBorder: "#e2e8f0", previewUnderlineOnly: false,
  },

  // ── 3. Elegante — Dark glass sofisticado ──────────────────────────────────
  elegante: {
    name: "Elegante",
    hint: "Dark glass premium",
    layout: "floating",
    overlayBg: "rgba(10,10,25,0.75)",
    overlayBlur: "blur(24px)",
    cardBg: "rgba(22,28,48,0.92)",
    cardBackdrop: "blur(20px) saturate(150%)",
    cardMaxWidth: "max-w-3xl",
    cardRadius: "rounded-3xl",
    cardShadow: "shadow-[0_40px_100px_-10px_rgba(0,0,0,0.7),inset_0_1px_0_rgba(255,255,255,0.08)]",
    barClass: "border-white/8 bg-white/4",
    inp: "w-full text-sm px-4 py-3.5 rounded-2xl bg-white/6 border border-white/10 focus:outline-none focus:border-[var(--t-from)]/70 focus:bg-white/10 text-white placeholder-white/25 font-medium transition-all",
    labelClass: "block text-[9px] font-black text-white/40 uppercase tracking-[0.14em] mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-white",
    cancelClass: "bg-white/8 border border-white/12 text-white/60 hover:bg-white/14",
    isDark: true,
    previewLayout: "floating",
    previewOverlay: "rgba(10,10,25,0.75)",
    previewBg: "rgba(22,28,48,0.92)",
    previewBar: "rgba(255,255,255,0.04)", previewInp: "rgba(255,255,255,0.06)",
    previewBorder: "rgba(255,255,255,0.10)", previewUnderlineOnly: false,
  },

  // ── 4. Tarjeta — Acento de color + fondo blanco ────────────────────────────
  tarjeta: {
    name: "Tarjeta",
    hint: "Acento + blanco",
    layout: "floating",
    overlayBg: "rgba(15,15,35,0.65)",
    overlayBlur: "blur(20px)",
    cardBg: "#ffffff",
    cardMaxWidth: "max-w-3xl",
    cardRadius: "rounded-2xl",
    cardShadow: "shadow-[0_32px_80px_-10px_rgba(0,0,0,0.35)]",
    accentBar: "linear-gradient(100deg,var(--t-from),var(--t-to))",
    barClass: "border-transparent bg-transparent",
    inp: "w-full text-sm px-4 py-3.5 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:border-[var(--t-from)] text-slate-800 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-[9px] font-black text-slate-400 uppercase tracking-[0.14em] mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-white",
    cancelClass: "bg-white/20 border border-white/30 text-white hover:bg-white/30",
    isDark: false,
    previewLayout: "floating",
    previewOverlay: "rgba(15,15,35,0.65)",
    previewBg: "#ffffff",
    previewBar: "linear-gradient(100deg,var(--t-from),var(--t-to))", previewInp: "#f1f5f9",
    previewBorder: "#e2e8f0", previewUnderlineOnly: false,
  },

  // ── 5. App — Dark Navy con acento eléctrico ────────────────────────────────
  app: {
    name: "App",
    hint: "Dark Navy eléctrico",
    layout: "floating",
    overlayBg: "rgba(2,4,18,0.92)",
    overlayBlur: "blur(28px)",
    cardBg: "#0d1224",
    cardMaxWidth: "max-w-2xl",
    cardRadius: "rounded-3xl",
    cardShadow: "shadow-[0_50px_120px_-15px_rgba(99,102,241,0.25),0_20px_50px_-10px_rgba(0,0,0,0.8)]",
    accentBar: "linear-gradient(100deg,var(--t-from),var(--t-to),var(--t-from))",
    barClass: "border-white/5 bg-black/20",
    inp: "w-full text-sm px-4 py-3.5 rounded-xl bg-white/5 border border-white/8 focus:outline-none focus:border-[var(--t-from)]/60 focus:bg-white/8 text-white placeholder-white/20 font-medium transition-all",
    labelClass: "block text-[9px] font-black uppercase tracking-[0.14em] mb-1.5",
    labelStyle: { color: "var(--t-from)", opacity: 0.7 },
    inpStyle: undefined,
    titleClass: "text-white",
    cancelClass: "bg-white/6 border border-white/10 text-white/50 hover:bg-white/10",
    isDark: true,
    previewLayout: "floating",
    previewOverlay: "rgba(2,4,18,0.92)",
    previewBg: "#0d1224",
    previewBar: "linear-gradient(100deg,var(--t-from),var(--t-to))", previewInp: "rgba(255,255,255,0.05)",
    previewBorder: "rgba(255,255,255,0.08)", previewUnderlineOnly: false, previewIsGreen: false,
  },

  // ── 6. Minimal — Frosted light (como Notion/Figma) ─────────────────────────
  minimal: {
    name: "Minimal",
    hint: "Frosted claro",
    layout: "floating",
    overlayBg: "rgba(241,245,249,0.8)",
    overlayBlur: "blur(12px)",
    cardBg: "#ffffff",
    cardMaxWidth: "max-w-2xl",
    cardRadius: "rounded-2xl",
    cardShadow: "shadow-[0_8px_50px_-8px_rgba(0,0,0,0.14),0_2px_10px_-2px_rgba(0,0,0,0.08)]",
    barClass: "border-slate-100 bg-white",
    inp: "w-full text-sm px-1 py-3 bg-transparent border-0 border-b border-slate-200 focus:outline-none focus:border-[var(--t-from)] text-slate-800 placeholder-slate-300 font-medium transition-all rounded-none",
    labelClass: "block text-[9px] font-black text-slate-400 uppercase tracking-[0.16em] mb-1",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-slate-900",
    cancelClass: "text-slate-400 hover:text-slate-700 font-bold transition-colors",
    isDark: false,
    previewLayout: "floating",
    previewOverlay: "rgba(241,245,249,0.8)",
    previewBg: "#ffffff",
    previewBar: "#ffffff", previewInp: "transparent",
    previewBorder: "#e2e8f0", previewUnderlineOnly: true,
  },

  // ── 7. Cristal — Glass flotante (favorito del usuario) ────────────────────
  cristal: {
    name: "Cristal",
    hint: "Vidrio flotante",
    layout: "floating",
    overlayBg: "linear-gradient(135deg,rgba(56,189,248,0.18),rgba(99,102,241,0.14))",
    overlayBlur: "blur(20px)",
    cardBg: "rgba(255,255,255,0.75)",
    cardBackdrop: "blur(24px) saturate(180%)",
    cardMaxWidth: "max-w-3xl",
    cardRadius: "rounded-3xl",
    cardShadow: "shadow-[0_24px_60px_-8px_rgba(99,102,241,0.25),inset_0_1px_0_rgba(255,255,255,0.9)]",
    barClass: "border-white/50 bg-white/30",
    inp: "w-full text-sm px-4 py-3.5 rounded-2xl bg-white/60 border border-sky-200/70 focus:outline-none focus:border-[var(--t-from)] focus:bg-white text-slate-800 placeholder-slate-400 font-medium transition-all",
    labelClass: "block text-[9px] font-black text-sky-600/80 uppercase tracking-[0.14em] mb-1.5",
    labelStyle: undefined, inpStyle: undefined,
    titleClass: "text-slate-800",
    cancelClass: "bg-white/50 border border-white/60 text-slate-600 hover:bg-white/80",
    isDark: false,
    previewLayout: "floating",
    previewOverlay: "linear-gradient(135deg,rgba(56,189,248,0.18),rgba(99,102,241,0.14))",
    previewBg: "rgba(255,255,255,0.75)",
    previewBar: "rgba(255,255,255,0.35)", previewInp: "rgba(255,255,255,0.6)",
    previewBorder: "#bae6fd", previewUnderlineOnly: false,
  },
};

export const FORM_DESIGN_ORDER = ["aurora", "flotante", "elegante", "tarjeta", "app", "minimal", "cristal"];
